### ISSUE TITLE
New field entity

### ISSUE THREAD

**Issue by Arkos13** [DariusIII/php-itunes-api#3]
Can you add an artWork100 field for a track entity? Or give the ability to get data without being converted to an entity.

**Comment by DariusIII** [comment]
Will check it out. Can you give me an example for it?

**Comment by Arkos13** [comment]
For example, here is https://github.com/DariusIII/php-itunesapi/blob/master/src/Providers/TrackProvider.php#L31. Just do not use the map method and then there will be no conversion to etity and, accordingly, all fields will be displayed. It will be very convenient if the use of the map method will be optional.

**Comment by DariusIII** [comment]
I did not mean example in the code, i meant example data returned from iTunes.

**Comment by Arkos13** [comment]
Sorry. Here, for example, the response for the track. In my case, I would like to add artworkUrl100.

`{"wrapperType":"track",
 "kind":"song",
 "artistId":909253,
 "collectionId":120954021,
 "trackId":120954025,
 "artistName":"Jack Johnson",
 "collectionName":"Sing-a-Longs and Lullabies for the Film Curious George",
 "trackName":"Upside Down",
 "collectionCensoredName":"Sing-a-Longs and Lullabies for the Film Curious George",
 "trackCensoredName":"Upside Down",
 "artistViewUrl":"https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewArtist?id=909253",
 "collectionViewUrl":"https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAlbum?i=120954025&amp;id=120954021&amp;s=143441",
 "trackViewUrl":"https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAlbum?i=120954025&amp;id=120954021&amp;s=143441",
 "previewUrl":"http://a1099.itunes.apple.com/r10/Music/f9/54/43/mzi.gqvqlvcq.aac.p.m4p",
 "artworkUrl60":"http://a1.itunes.apple.com/r10/Music/3b/6a/33/mzi.qzdqwsel.60x60-50.jpg",
 "artworkUrl100":"http://a1.itunes.apple.com/r10/Music/3b/6a/33/mzi.qzdqwsel.100x100-75.jpg",
 "collectionPrice":10.99,
 "trackPrice":0.99,
 "collectionExplicitness":"notExplicit",
 "trackExplicitness":"notExplicit",
 "discCount":1,
 "discNumber":1,
 "trackCount":14,
 "trackNumber":1,
 "trackTimeMillis":210743,
 "country":"USA",
 "currency":"USD",
 "primaryGenreName":"Rock"}`

If it is not difficult, then it is better to add all the fields at once, so that other users would not have such an issue.
